Repository Github-F4F-Detector/Github-F4F-Detector, pull requests merged in 2023-06, with the labels that each got.

#3 [LoginPage] 사용자 토큰 입력 뷰 구현
  next.config.js
  package.json
  pages/_app.tsx
  pages/login/index.tsx
  public/icon/index.ts
  public/icon/info_FILL0_wght400_GRAD0_opsz48.svg
  states/user.ts
  styles/globalStyle.ts
  yarn.lock
Labels: feat

#6 Feat#1/follow list
  .vscode/setting.json
  api/followData.ts
  api/hello.ts
  api/myProfileData.ts
  components/followList/AllCheckBox.tsx
  components/followList/CheckBox.tsx
  components/followList/FollowListBody.tsx
  components/followList/FollowListItem.tsx
  components/followList/FollowListMap.tsx
  components/followList/MyProfile.tsx
  package.json
  pages/follow-list/index.tsx
  public/icon/ListBackgroundIcon.svg
  public/icon/allCheckBoxIcon.svg
  public/icon/index.ts
  public/icon/nonCheckBoxIcon.svg
  public/image/Group 986126.png
  states/check.ts
  types/userTypes.ts
  yarn.lock
Labels: feat, style, refactor, chore

#7 [Follow] 맞팔되지 않은 사용자 맞팔하기 구현
  api/followUser.ts
  api/index.ts
  components/followList/CheckBox.tsx
  components/followList/FollowListBody.tsx
  components/followList/FollowListItem.tsx
  hooks/hello.ts
  hooks/user.ts
  public/icon/chevron_bottom.svg
  public/icon/index.ts
  states/follow.ts
  states/user.ts
Labels: feat

#10 Feat#9/code refactoring
  api/followData.ts
  api/myProfileData.ts
  components/common/ErrorPage.tsx
  components/common/LoadingPage.tsx
  components/followList/CheckBox.tsx
  components/followList/FollowListBody.tsx
  components/followList/FollowListItem.tsx
  components/followList/FollowListMap.tsx
  components/followList/MyProfile.tsx
  hooks/user.ts
  package.json
  pages/_app.tsx
  pages/follow-list/index.tsx
  types/fetchFollowingInfoTypes.ts
  types/myProfile.ts
  types/userTypes.ts
  yarn.lock
Labels: refactor, chore
